version: "3.8"

services:
  app:
    build: .
    image: flask-redis-app:latest
    container_name: flask_app
    environment:
      FLASK_DEBUG: 1
      DATABASE_URL: postgresql://myuser:mypassword@postgres:5432/mydatabase
      REDIS_URL: redis://redis:6379/0
    ports:
      - "5001:5001"
    depends_on:
      - postgres
      - redis
    networks:
      - mynet

networks:
  mynet:
    external: true
