version: "3.9"

services:
  flask_app:
    image: bhushan04ec041/jenkins_python_app:v1.0.4
    container_name: flask_app
    restart: unless-stopped
    ports:
      - "5001:5001"
    networks:
      - mynet
    environment:
      # Optional: Add env vars if your app.py reads from env
      POSTGRES_HOST: postgres
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      REDIS_HOST: redis

networks:
  mynet:
    external: true
