version: "3"

services:
  app:
    build: .
    image: takacsmark/flask-redis:1.1
    environment:
      - FLASK_DEBUG=1
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/usr/src/app

  redis:
    image: redis:4.0.11-alpine

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/log:/var/log
      - ./postgres/init:/docker-entrypoint-initdb.d