version: "3.8"

services:
  app:
    build: .
    image: flask-redis-app:latest
    container_name: flask_app
    environment:
      - FLASK_DEBUG=1
    ports:
      - "5001:5001"
    volumes:
      - .:/usr/src/app
    networks:
      - mynet   # ✅ connect to same network

networks:
  mynet:
    external: true   # ✅ attach to existing network
