version: "3.8"

services:
  app:
    build: .
    image: flask-redis-app:latest
    environment:
      - FLASK_DEBUG=1
    ports:
      - "5001:5001"
    volumes:
      - .:/usr/src/app
    networks:
      - mynet

networks:
  mynet:
    driver: bridge